### ISSUE TITLE
An internal error occurred during: "Update" when showing FluentMark view

### ISSUE THREAD

**Issue by SimonKagstrom** [grosenberg/fluentmark#11]
Unfortunately, I can't get FluentMark to work at all: When creating a md file, any letter I write will cause the above error (details show just NullPointerException without a backtrace).

OS: Ubuntu 16.04
Eclipse version: neon.3
FluentMark version:   0.10.0.20170410-1718

I have pandadoc and graphviz installed, not sure if there is other requirements as well.

Anyway, thanks for writing this tool!

**Comment by grosenberg** [comment]
What is reported about the error in the Eclipse log file? What web browser is installed (and accessible from the Fluentmark process).

Please provide information identifying exactly when and where the error is occurring in use.

**Comment by SimonKagstrom** [comment]
OK, thanks for the hints. I'm not very familiar with debugging Eclipse itself. Here is the entries from the Eclipse log:

```
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.cpp.product

org.eclipse.core.jobs
Error
Fri May 05 09:12:29 CEST 2017
An internal error occurred during: "Update".

java.lang.NullPointerException
	at net.certiv.fluentmark.editor.FluentMkEditor.find(FluentMkEditor.java:637)
	at net.certiv.fluentmark.editor.FluentMkEditor.getStyles(FluentMkEditor.java:588)
	at net.certiv.fluentmark.editor.FluentMkEditor.getHtml(FluentMkEditor.java:545)
	at net.certiv.fluentmark.views.UpdateJob.run(UpdateJob.java:81)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

In Eclipse, the Web browser is set to the internal browser. I also tested Chromium and Firefox as external browsers with the same result.

**Comment by grosenberg** [comment]
Ok.  This is due to a problem finding the CSS stylesheet for the view. Initial guess is that it is something peculiar to your setup.

Are you running in a container or other virtualized environment?  What is the filesystem path to the workspace? Anything not purely standard in how/where you installed Eclipse?

Are you using a custom or default stylesheet (preference)?  If custom, where is it located on the filesystem? Does it have adequate read permissions? Is it in a linked directory?

**Comment by grosenberg** [comment]
I have pushed an update that should prevent the NPE. Let me know if this fixes the problem you are experiencing.

**Comment by SimonKagstrom** [comment]
Works like a charm, thanks!
