### ISSUE TITLE
0.12.0.20170721-0031: space key ignored

### ISSUE THREAD

**Issue by jouvin** [grosenberg/fluentmark#16]
I just upgraded my Eclipse installation (20170314-1500) and FluentMark was updated from 0.9 (if I'm right) to 0.12.0.20170721-0031. Since then, FluentMark refuses to enter any space in the edited file... Is there something trivial that I made wrong?

**Comment by grosenberg** [comment]
Cannot reproduce. Runs correctly on the current version of Oxygen 4.7 (20170620-1800).

**Comment by jouvin** [comment]
I just updated from Mars to Oxygen and I confirm that I don't see the problem with Oxygen... As for me, the issue can be closed.
