### ISSUE TITLE
Shortcuts/keybindings when editing Markdown.

### ISSUE THREAD

**Issue by Elisedlund** [grosenberg/fluentmark#18]
Many markdown editors support shortcuts/keybindings to do some useful things. 
Example: 
Ctrl+B = make things bold, by surrounding marked with ** **
Ctrl+I = make things italic, by surrounding marked with _ _

I find these shortcuts are extremely useful when editing markdown and they are supported it **THIS** editor I'm typing right now, 
Its also supported by the other tools like the forum Discourse which also uses markdown.

**Comment by grosenberg** [comment]
Added in 0.14
