### ISSUE TITLE
Dependency on specific bundle minor versions

### ISSUE THREAD

**Issue by jensli** [grosenberg/fluentmark#2]
I had some trouble when I tried to installed FluentMark because it declares a dependency on the version 3.12.2 of bundle  `org.eclipse.jdt.ui`.

I believe that it would be more appropriate to declare a dependency on version 3.0.0 or version 3.12.0 or something like that.

The same goes for other dependencies.

 See http://wiki.eclipse.org/Version_Numbering.

The error message I was confronted with was the following:

    Cannot complete the install because of a conflicting dependency.
      Software being installed: FluentMark Editor 0.9.1.20170130-0509 (net.certiv.fluentmark.feature.feature.group 0.9.1.20170130-0509)
      Software currently installed: Eclipse Java Development Tools 3.12.0.v20160606-1100 (org.eclipse.jdt.feature.group 3.12.0.v20160606-1100)
      Only one of the following can be installed at once: 
        Java Development Tools UI 3.12.1.v20160822-0645 (org.eclipse.jdt.ui 3.12.1.v20160822-0645)
        Java Development Tools UI 3.12.0.v20160525-1829 (org.eclipse.jdt.ui 3.12.0.v20160525-1829)
        Java Development Tools UI 3.12.2.v20160929-0804 (org.eclipse.jdt.ui 3.12.2.v20160929-0804)
      Cannot satisfy dependency:
        From: FluentMark Editor 0.9.1.20170130-0509 (net.certiv.fluentmark 0.9.1.20170130-0509)
        To: bundle org.eclipse.jdt.ui 3.12.2
      Cannot satisfy dependency:
        From: FluentMark Editor 0.9.1.20170130-0509 (net.certiv.fluentmark.feature.feature.group 0.9.1.20170130-0509)
        To: net.certiv.fluentmark [0.9.1.20170130-0509]
      Cannot satisfy dependency:
        From: Eclipse Java Development Tools 3.12.0.v20160606-1100 (org.eclipse.jdt.feature.group 3.12.0.v20160606-1100)
        To: org.eclipse.jdt.ui [3.12.0.v20160525-1829]

PS: When I come to think of it, it's a bit weird that a Markdown plug-in has a dependency on JDT.

FluentMark version: 0.9.1.20170130-0509
Eclipse version: Neon.2 Release (4.6.2) Build id: 20161208-0600
OS: Windows 10

**Comment by grosenberg** [comment]
The versions required are those that the plugin has been tested with.
