### ISSUE TITLE
Error Dialog on a bad dot grammar usage.

### ISSUE THREAD

**Issue by chhil** [grosenberg/fluentmark#23]
Hello,

Recently added this to eclipse through the marketplace.
This is the **detail** error of the dialog that pops up and cannot be closed until you close the editor.

```
An error has occurred. See error log for more details.
net.certiv.fluentmark.model.PageRoot cannot be cast to net.certiv.fluentmark.model.PagePart

```
I was trying to use a dot example (without the ~~~ dot)

```
graph {
    a -- b;
    b -- c;
    a -- c;
    d -- c;
    e -- c;
    e -- a;
}
```

p.s. I hadn't done this ->To use DOT, install Graphviz. Then, in the FluentMark Converter preferences for DOT, browse to and select the dot executable.

**Comment by grosenberg** [comment]
Unable to reproduce.
