### ISSUE TITLE
Not installable while using LiClipse Feature 4.3.0

### ISSUE THREAD

**Issue by pprossi** [grosenberg/fluentmark#24]
Seems it gives a dependency error on eclipse.spellchecker.

Liclipse -> 4.3.0.201711051152
FluentMark -> 3.3.0.20161216-0034

the only option is to uninstall LiClipse Feature?

details below:

Cannot complete the install because of a conflicting dependency.
  Software being installed: FluentMark Editor 0.15.0.20171223-2156 (net.certiv.fluentmark.feature.feature.group 0.15.0.20171223-2156)
  Software currently installed: LiClipse Feature 4.3.0.201711051152 (com.brainwy.liclipse.feature.feature.group 4.3.0.201711051152)
  Only one of the following can be installed at once: 
    Spellchecker 4.4.0.201711281546 (eclipse.spellchecker 4.4.0.201711281546)
    Spellchecker 4.3.0.201711051152 (eclipse.spellchecker 4.3.0.201711051152)
    Spellchecker 3.3.0.20161216-0034 (eclipse.spellchecker 3.3.0.20161216-0034)
  Cannot satisfy dependency:
    From: LiClipse Feature 4.3.0.201711051152 (com.brainwy.liclipse.feature.feature.group 4.3.0.201711051152)
    To: eclipse.spellchecker [4.3.0.201711051152]
  Cannot satisfy dependency:
    From: Spellchecker 3.3.0.20161216-0034 (eclipse.spellchecker.feature.feature.group 3.3.0.20161216-0034)
    To: eclipse.spellchecker [3.3.0.20161216-0034]
  Cannot satisfy dependency:
    From: FluentMark Editor 0.15.0.20171223-2156 (net.certiv.fluentmark.feature.feature.group 0.15.0.20171223-2156)
    To: eclipse.spellchecker.feature.feature.group [3.3.0.20161216-0034]

**Comment by grosenberg** [comment]
The namespace for the Fluentmark spellchecker has been changed for the next version.
