### ISSUE TITLE
Enable PlantUML rendering for TxtMark

### ISSUE THREAD

**Issue by Nicolous** [grosenberg/Fluentmark#29]
I'm using FluentMark 1.2.0.20180807-2118 on Eclipse Photon 4.8.0 (Windows).

By default PlantUML rendering is disabled and TxtMark is set as converter.
The issue is: PlantUML rendering can only be activated for TxtMark by selecting the Pandoc converter  (even if pandoc is not installed), checking the box "Enable PlantUML rendering", and switching back to the TxtMark converter.

I would have expected this checkbox to be in each converter that supports it.

Nice plugin by the way.

**Comment by grosenberg** [comment]
Not currently supported for any converter other than Pandoc.

**Comment by grosenberg** [comment]
Fixed in current release.
