### ISSUE TITLE
Comment command create TWO undo-actions

### ISSUE THREAD

**Issue by jensli** [grosenberg/fluentmark#3]
When the comment command is activated `<!--` and `-->` is inserted around the selected text.

When the undo command is activated both of these should be removed by one undo action. But they are undo-ed separately, so it takes two undo:s to get rid of both of them. 

FluentMark version: 0.9.1.20170130-0509
Eclipse version: Neon.2 Release (4.6.2) Build id: 20161208-0600
OS: Windows 10

**Comment by grosenberg** [comment]
Added in v.15
