### ISSUE TITLE
Cannot complete the install because one or more required items could not be found.

### ISSUE THREAD

**Issue by JonathanBelanger** [grosenberg/fluentmark#32]
I have an environment that does not have general internet access, so I need to move files via the tried and true sneaker net.  Anyway, I got the installation for Fluentmark and attempted to install it, but I got the following error:

    Software being installed: FluentMark Editor 1.2.20180807-2118 
        (net.certiv.fluentmark.feature.feature.group 1.2.0.20180807-2118)
    Missing requirement: Fluentmark Editor 1.2.0.20180807-2118 
        (net.certiv.fluentmark.feature.feature.group 1.2.0.20180807-2118) requires
    "org.eclipse.equinox.p2.iu; org.eclipse.jdt.ui 0.0.0" could not be found`

What eclipse packages may I be missing?

**Comment by grosenberg** [comment]
org.eclipse.equinox.p2.iu -- a really basic part of the Eclipse platform necessary to install plugins from standard P2 repositories. 

org.eclipse.jdt.ui -- the Java editor system (JDT).

To do something like this, you really need to 
-- 1) start a standard Eclipse/Java package (https://www.eclipse.org/downloads/packages/release/2018-12/r/eclipse-ide-java-developers) installation
-- 2) get a copy of the Fluentmark update site (attached)
[net.certiv.fluentmark.site.zip](https://github.com/grosenberg/fluentmark/files/2758327/net.certiv.fluentmark.site.zip)
-- 3) use Eclipse to install from from the zipped update site.

Beyond this bit of advise, I cannot help further.
Best of luck!
