### ISSUE TITLE
Tables don't display

### ISSUE THREAD

**Issue by kferrone** [grosenberg/Fluentmark#34]
Tables do not display in the viewer. The raw pipe characters are displayed instead. 

To reproduce simply make a table and view in the viewer.

**Comment by wti** [comment]
Valid tables work for me.  Use an empty line before and after, a header, and a separator.  For data, only internal separator is required.  E.g., put in your document the following text: 

```

|one|two|
|---|---|
|1|2|
1|2

```

**Comment by aemyers** [comment]
Same issue here.

![image](https://user-images.githubusercontent.com/32523187/58064315-6d142d00-7b36-11e9-9461-78384e4c4926.png)

**Comment by aemyers** [comment]
Could this be related to using Eclipse 2019-03 (4.11)?

I just noticed it is not on the list of supported Eclipse versions.... :(

**Comment by kferrone** [comment]
I am also on `2019-03` and I see what @aemyers sees too.

**Comment by davidjmemmett** [comment]
I've just installed this plugin (the auto-formatting feature & table editor are amazing), however I can confirm that tables aren't previewing correctly using the following builds of Eclipse & FluentMark.

**Eclipse**: `Version: 2019-03 (4.11.0) Build id: 20190314-1200`
**FluentMark** (Installed from Eclipse Marketplace): `1.2.0.20180807-2118`

**Comment by MarcusWolschon** [comment]
When will this 3 month old bug be fixed?
Tables are not only not previewed but the HTML export also doesn't export them.

**Comment by RobertK66** [comment]
I am using the latest version of NXP MCUXpresso for embedded development. It is based on Eclipse Platform 4.10.0v20181206-0815. Unfortunately I also hit this bug. As I am stick with this eclipse version I would appreciate any info if this is going to be fixed any time soon. Thx.

**Comment by N0rbert** [comment]
Still happens with simpliest [tables ever](https://www.markdownguide.org/extended-syntax/) :

```
| Syntax      | Description | Test Text     |
| :---        |    :----:   |          ---: |
| Header      | Title       | Here's this   |
| Paragraph   | Text        | And more      |
```

**Comment by MarcusWolschon** [comment]
Reported in April 2019.
Still happens in August 2020 and no reaction :/

**Comment by mrgou** [comment]
I had to select `blackfriday` as a converter for this to work.
