### ISSUE TITLE
Large complex documents are slow to edit

### ISSUE THREAD

**Issue by wti** [grosenberg/fluentmark#36]
(I realize this is vague, but I'm sure you're aware of the issue; this is mainly to ask if you have a solution in mind, and perhaps need help.)

I have many large markdown documents, and I find the editor to slow my typing and editing significantly.  My guess is that typing, particularly changing structural elements like sublists and headers, causes the entire document to be reparsed because the underlying markdown parser does not support incremental updates/compilation.

If that's the problem and you have a solution (or know there isn't one), great.  

(fwiw, I don't believe the problems is outliner/editor hysteresis from my last issue, since I get the slowness even when the outline view is not open.)

If the parser is already incremental and you think it depends on the document and there may be structure-specific or degenerate issues (e.g. with mis-formatting like no empty lines before the headers), then I can work to create some reproducible cases if that would help.

**Comment by grosenberg** [comment]
Cannot reproduce.
