### ISSUE TITLE
Feature request: (pluggable?) linter

### ISSUE THREAD

**Issue by wti** [grosenberg/fluentmark#37]
I find myself constantly forgetting markdown idiosyncracies until I manually check the output.  It would be nice to get squiggles e.g., when there are no extra lines before headlines or tables.

I realize that syntax varies significantly, so I wonder if this should be a pluggable thing.

I noticed a plugin that allows the user to configure a tool to generate problem markers:  it could be a solution to recommend to users, to adapt, or to borrow ideas from: https://github.com/wrygiel/eclipse-external-problem-marker.  It just runs the tool, snoops the stdout, and converts the results into problem markers.  (It unfortunately assumes the file is on each line, while some tools put the file above the error line.)  

(btw, I use pandoc for output along with my own customized templates.  The fluentmark display window is great, but I'm invested in my reproducible document pipeline, and thus even being able to manually check that window isn't the best solution for me at least.)

**Comment by grosenberg** [comment]
Fluentmark fully supports error and warning markers, including spellcheck with quick fix. Have not found a linter that can heuristically analyze intent and provide suggestions.
