### ISSUE TITLE
User documentation missing

### ISSUE THREAD

**Issue by MarcusWolschon** [grosenberg/Fluentmark#39]
After installing Fluentmark using the Eclipse Marketplace there is no user documentation on how to use it.

Opening a .md file will edit it using the "FluentMark Editor" but no "FluentMark View" to preview it.
The editor shows no toolbar inside the editor for any markup and the user is not informed about the few keyboard shortcuts mentions in the README.md here on GitHub.
The 3 new toolbar items are easy to miss in the large toolbar on modern high resolution and high DPI screens.
There are also no entries in the context menu inside the editor or on .md files .

There should be hints and helpful, visible tools inside the editor to make it usable for first time users.

**Comment by ericbarnhill** [comment]
I concur with this assessment. I have installed this plugin and all I see is a plain text window. If there is any markdown support it is not apparent and there is no documentation to explain where it is.

It is inconceivable to me that the developer could be describing this plugin as a fully featured markdown editor and this does not seem like truth in advertising.

**Comment by grosenberg** [comment]
Exactly what, consistent with the philosophy of standard Eclipse editors, were you expecting?

**Comment by MarcusWolschon** [comment]
> Exactly what, consistent with the philosophy of standard Eclipse editors, were you expecting?

The expected features are listed in the initial posting.
