### ISSUE TITLE
Problem with GUI controls on Converters preferences page

### ISSUE THREAD

**Issue by jensli** [grosenberg/fluentmark#4]
1. When a checkbox is clicked then the whole panel is set to a disabled state.
2. When user types in a text field and that results in a validation error, the text field loses focus. 

FluentMark version: 0.9.1.20170130-0509
Eclipse version: Neon.2 Release (4.6.2) Build id: 20161208-0600
OS: Windows 10

**Comment by grosenberg** [comment]
Fixed with v0.10.0.
