### ISSUE TITLE
Decoding error in the view when using PanDoc

### ISSUE THREAD

**Issue by dannchr** [grosenberg/Fluentmark#41]
On Windows, using the PanDoc converter, I get the error message
`UTF-8 decoding error in - at byte offset 12374 (ab). The input must be a UTF-8 encoded text. `
 in the FluentMark View if using non-ascii characters (e.g. æ, ø, å, ô) even though the file in the editor is UTF-8 encoded.

This also happens if i just insert two consecutive greater than characters ">>", which is preventing the preview from displaying PlantUML diagrams containing stereotypes.

I think the problem is that the content of the editor is written to the PanDoc converter in the default (platform specific) encoding. I took a look at the code in the master branch and if I have understood it right, the file is written to PanDoc in net.certiv.fluentmark.util.Cmd.process():
```
	OutputStreamWriter out = new OutputStreamWriter(process.getOutputStream());
```
This constructor of OutputStreamWriter uses the platform specific encoding, so based on [this stackoverflow comment](https://stackoverflow.com/a/9853261) I think it should probably be changed to something like:
```
	OutputStreamWriter out = new OutputStreamWriter(process.getOutputStream(), Charset.forName("UTF-8").newEncoder());
```
to explicitly set the output encoding to UTF-8, at least when the converter is PanDoc. Perhaps it should be parametrized if UTF-8 is not the right choice for all converters. I think this will even make it work if the file is written in a completely different encoding, as long as eclipse is aware of the correct encoding of the source file.

I have not figured out how to setup the project so I can test it, so I have not tried out this solution. But if I add: `-Dfile.encoding=UTF-8` argument to eclipse to make UTF-8 the default encoding, it displays fine without any conversion errors, with the exact same file, which I think confirms that this solution should work.

**Comment by famod** [comment]
Same here.

Btw: Suggestion for the fix:
```new OutputStreamWriter(process.getOutputStream(), StandardCharsets.UTF_8)```

**Comment by grosenberg** [comment]
Fixed in current release.
