### ISSUE TITLE
Open webpage in internal web browser

### ISSUE THREAD

**Issue by mattcarp12** [grosenberg/fluentmark#42]
If I'm editing a markdown document that contains a hyperlink and then click on that link in the fluentmark viewer, the webpage is opened in the fluentmark viewer. It should be opened in the eclipse internal web browser instead.

**Comment by grosenberg** [comment]
The viewer contains/is implemented using an embedded web-browser.  Don't believe there is any way to change the current behavior. Other than not being the desired behavior, is there any specific problem?
