### ISSUE TITLE
Synchronized vertical scroll

### ISSUE THREAD

**Issue by Amenel** [grosenberg/Fluentmark#44]
This is a suggestion for an enhancement that could solve one of the problems I encounter. I haven't found yet a means to have the FluentMark view vertically synchronized with the active editor. 

For short documents, it's no big deal to manually scroll the rendering view in order to see how the text being edited is rendered. But it gets a bit more cumbersome for long documents. So I thought of solutions that could alleviate this issue.

Solution 1 would replicate the behavior of the WikiText editor: the **Link with Editor** button would affect both the editor and the view. But this feels weird here because the view is not embedded as a tab within the editor like it is with WikiText. Moreover, I wonder how the Outline view would know which of the editor or view to target.

Solution 2 would be to synchronize the view with the current editor à la Notepad++'s **Synchronize Vertical Scrolling**, using a new button in the toolbar of the view, maybe between the buttons for refreshing the view and the button for opening stylesheet preferences. That way, the view will scroll when the editor is scrolled, but not the other way around: scrolling the view will not affect the editor.

Just a suggestion, I don't know how technically feasible it would be!

**Comment by grosenberg** [comment]
First real attempt at implementing vertical scroll sync is in version 1.8, just released.
