### ISSUE TITLE
Unable to activate PlantUML support

### ISSUE THREAD

**Issue by anthonyanjorin** [grosenberg/Fluentmark#48]
I have installed the latest versions of fluentmark (from `http://www.certiv.net/updates`) as well as pandoc.

Although support for PlantUML should be available, there are no preferences for this and the editor does not seem to recognise the starting and ending `@startuml`, `@enduml` tags (as in the tags are not recognised as keywords, there are no templates, and they are not syntax highlighted in any way).  The view just displays the text verbatim without rending the expected image.  

Dot works just fine.  
I have chosen pandoc as converter thanks to #29.
My plantuml fragments can be recognised and rendered using plantuml directly.
I am using Windows and Eclipse DSL Tools, Version: 2019-12 (4.14.0)

**Comment by beatrizsanchez** [comment]
I am having the same issue

**Comment by grosenberg** [comment]
PlantUML requires Graphviz to be installed.

**Comment by beatrizsanchez** [comment]
yes, it does, just like rendering dot which works very well, but for some reason plantuml doesn't

**Comment by grosenberg** [comment]
Please attach a minimal markdown document that reproduces the problem: that dot graph works but uml graph does not.

**Comment by beatrizsanchez** [comment]
Sure here it is. Graphviz works as well within the back tick environment, and plantuml doesn't within or outside the ``` or ~~~ environments.
I am using the updatesite to install fluentmark but I believe is not using the latest version of the code with support for plantuml, it may just be a matter of releasing the newest version
```
## Graphviz Dot
~~~ dot

digraph G {
 Bob -> Alice [label="Hello"]
}

~~~

## PlantUML

@startuml
Bob->Alice : hello
@enduml
```
![image](https://user-images.githubusercontent.com/6515216/83391946-2feea600-a3ec-11ea-98db-4daffd3d894a.png)
![image](https://user-images.githubusercontent.com/6515216/83391684-be165c80-a3eb-11ea-9503-62fad9a11232.png)
![image](https://user-images.githubusercontent.com/6515216/83391876-13526e00-a3ec-11ea-9ab9-88b1a8abde3d.png)

**Comment by grosenberg** [comment]
Looks like a Windows OS.  Either give Fluentmark an absolute filesystem path to the Dot executable or per the `README`:

> If Graphviz is installed in a non-default directory, set the GRAPHVIZ_DOT environment variable to the actual installation directory.

**Comment by beatrizsanchez** [comment]
Hi @grosenberg, thanks for helping out with this. I've already set the variable, any other ideas?

**Comment by grosenberg** [comment]
What OS and version? 
Did you install Graphviz for `everyone/all accounts`? 
What is the actual full path to the `dot.exe` executable
What did you put in the `GRAPHVIZ_DOT` environment variable?

**Comment by Marcay1909** [comment]
Same problem here, did you consider beatrizsanchez comment

> However it seems that this contribution was added after the update site was generated. The update site was published in Feb 2018 and the support for plant uml seems to have been added in Aug that year

Version available via Eclipse Update Site is 1.0.0.**20180222**-2348, which also seems like the version was released before UML-support

**Comment by grosenberg** [comment]
Yes, of course, and that not the issue. The root problem is that the PlantUML jar must be independently capable of finding the dot executable. See the PlantUML README, etc. for more details.

Unfortunately, relying on the system PATH/relative paths is not sufficient as you and @beatrizsanchez are apparently doing, at least given the supporting information provided.

**Comment by mrgou** [comment]
Same problem on a clean install of Eclipse (2020-12 (4.18.0)) and FluentMark, with graphviz 2.44.1 and the `GRAPHVIZ_DOT` environment variable set to the directory containing `dot.exe` on Windows 10, using `blackfriday` as converter.

![Screenshot 2021-01-11 144822](https://user-images.githubusercontent.com/5311753/104190410-5b268280-541c-11eb-995d-86a8f3593ad3.png)

**Comment by grosenberg** [comment]
Works in current release.
