### ISSUE TITLE
Pandoc HTML text encoding issues

### ISSUE THREAD

**Issue by jensli** [grosenberg/fluentmark#5]
1. Weird characters, for example `å`, `ä` and `ö` are not handled properly. A opening a FluentMark editor on a file with these characters makes the FluentMark view display the following message:

 ```
pandoc.exe: Cannot decode byte '\xf6': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
```

This seems to happens regardless of what text encoding scheme the file is configured to have in Eclipse.

2. When the *Converters* -> *Pandoc Options* -> *Use Stmart Typography* settings is enabled, then the `'` character is rendered as `â€™` in the FluentMark view.

(The FluentMark *editor* doesn't exhibit any of these problems.)

FluentMark version: 0.9.1.20170130-0509
Eclipse version: Neon.2 Release (4.6.2) Build id: 20161208-0600
OS: Windows 10

**Comment by grosenberg** [comment]
This is a source document encoding problem. See this [Pandoc forum thread](https://groups.google.com/forum/#!topic/pandoc-discuss/S_qJTCBp-Zo).
