### ISSUE TITLE
Add more supported LaTeX equation formats

### ISSUE THREAD

**Issue by N0rbert** [grosenberg/Fluentmark#50]
### Describe your feature request

Many scientific texts contain equations. Currently texts are sometimes written in RMarkdown.

Some texts are books and articles written in [bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations), some of texts are presentations written with [xaringan](https://bookdown.org/yihui/rmarkdown/xaringan.html). 

### What problem does this feature solve?

Support many LaTeX equation notations such as:

```
Inline equation $f(x) = \sin(x)$

---

Environment `\begin{equation}...(\#eq:label)\end{equation}`
with auto-numbering and label (for bookdown):

\begin{equation}
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}

---

Environment `\begin{equation}...\label{label}\end{equation}`
with auto-numbering label for xaringan

\begin{equation}
  g\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
\label{binom2}
\end{equation}
```

Currently the rendering fails:

![fluentmark-math](https://user-images.githubusercontent.com/309456/81047136-8090e300-8ec2-11ea-805a-21f56aaa76a4.png)

### Additional context

This functionality is currently supported in VNote and ReText:

![retext-math](https://user-images.githubusercontent.com/309456/81047185-93a3b300-8ec2-11ea-8612-b9363f4cb98a.png)

In this feature request I ask only for rendering of equations. 
Auto-numbering is not needed for me.
I'll do it in RStudio after knitting of the document.

**Comment by grosenberg** [comment]
All of this should* work in the existing public version.

*but does not because of a bug in the defined priority of quoted strings relative to raw latex recognition (hint: remove the quoted latex, and it should work).

Fixed in the next version, which is a major upgrade.
