### ISSUE TITLE
Scroll bar disappears after choosing `neue.css` as Build-in Stylesheet

### ISSUE THREAD

**Issue by humphreygao** [grosenberg/Fluentmark#52]
See the screenshot below:

![scroll bar disapper](https://user-images.githubusercontent.com/52394598/82307569-1d8b6a00-99f3-11ea-9dd6-d16b5092974e.png)

**Comment by grosenberg** [comment]
What OS type/version, Eclipse version, and JDK version are you running.

**Comment by humphreygao** [comment]
Windows 10 Pro 64-bit
Eclipse 2020-03 (4.15.0)
Oracle JDK 1.8.0_251
