### ISSUE TITLE
Certificate problem with update site http://www.certiv.net/updates/

### ISSUE THREAD

**Issue by perlan** [grosenberg/Fluentmark#54]
I'm unable to install the fluentmark editor from  Eclipse marketplace due to a certificate error when trying to connect to http://www.certiv.net/updates/. It looks like the URL is redirecting to https://www.certiv.net/updates/ and the certificate served dose not include https://www.certiv.net in the subjectAltName. The current workaround is to manually use https://certiv.net/updates/.

The issue is easy to replicate using: curl -L -v http://www.certiv.net/updates/

**Comment by perlan** [comment]
Sorry, Using a manual update site doesn't work either since eclipse refuse to to actually install the plugin

**Comment by eraonel** [comment]
Unable to read repository at https://www.certiv.net/updates/content.xml.
Unable to read repository at https://www.certiv.net/updates/content.xml.
Certificate for <www.certiv.net> doesn't match any of the subject alternative names: [certiv.net]

**Comment by grosenberg** [comment]
Certificate fixed. Please try again.

**Comment by mpet** [comment]
Thanks it works!
