### ISSUE TITLE
Strikethrough does not work

### ISSUE THREAD

**Issue by TobiasBoeschMiele** [grosenberg/Fluentmark#55]
When I do \~\~test text\~\~ in FluentMark editor the text is not struck out in the Viewer.

![fluentmarkStrikeThrough](https://user-images.githubusercontent.com/64197724/98674765-9263af00-2359-11eb-9595-b5368c97b434.png)

Is that intended to happen? Is it an issue? Do I have to strike through somehow different?

**edit**: Is use FluentMark Editor	1.0.0.20180222-2348

**Comment by TobiasBoeschMiele** [comment]
Tables seem to be the same:

![fluentmarkTable](https://user-images.githubusercontent.com/64197724/98677384-3bf86f80-235d-11eb-9a50-4e5138b59d11.png)

**Comment by grosenberg** [comment]
Fixed in current release.
