### ISSUE TITLE
Markdown highlighting broken when dollar sign is used inside codeblock

### ISSUE THREAD

**Issue by amurashkin17** [grosenberg/Fluentmark#56]
The markdown below not highlighted at all (no bold, no code block highlighting) in the editor. The view renders it correctly.

~~~
**PATH=\$PWD**

```console
myuse$ saw
```
~~~

If a backslash is added before the second dollar, the highlighting is OK.

Also, the highlighting depends on the edit history. In the same example, if the backslash before the second dollar sign removed, the bold text is highlighted but the code block is not. After closing and opening the file, no highlighting again.

Installed Tools
Certiv Tools net.certiv.tools_1.0.7.20171212-2141
FluentMark Editor net.certiv.fluentmark_1.0.0.20180222-2348

**Comment by amurashkin17** [comment]
Adding the backslash before the dollar inside the code block is not a solution as the backslash is displayed when the markdown is rendered.

**PATH=\$PWD**

```console
myuse\$ saw
```

It seems that there is no way, at the same time, to correctly render and properly highlight such a markdown.

**Comment by grosenberg** [comment]
Fixed in current release.
