### ISSUE TITLE
Failed to filter doc partitions: null

### ISSUE THREAD

**Issue by amurashkin17** [grosenberg/Fluentmark#57]
Eclipse error log contains multiple error messages **Failed to filter doc partitions: null**

The error event details

```
eclipse.buildId=4.17.0.I20200902-1800
java.version=15
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Framework arguments:  -product org.eclipse.epp.package.javascript.product
Command-line arguments:  -data file:/home/mur/Workspace/Sawtooth/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.javascript.product

Plug-in: net.certiv.fluentmark
Error
Sat Nov 21 10:17:18 CST 2020
Failed to filter doc partitions: null

```

Installed Tools
```
Certiv Tools net.certiv.tools_1.0.7.20171212-2141
FluentMark Editor net.certiv.fluentmark_1.0.0.20180222-2348
```

**Comment by grosenberg** [comment]
Not unexpected.

**Comment by iloveeclipse** [comment]
What is the root cause of the problem & how one can get rid of those errors? They always shown on opening *any* text editor.

**Comment by cdietrich** [comment]
I propose to do the same as the jdt spelling engine does and simply ignore the exception instead of logging it

**Comment by iloveeclipse** [comment]
And the stack is...?

**Comment by cdietrich** [comment]
`org.eclipse.jdt.internal.ui.text.spelling.JavaSpellingEngine.check(IDocument, IRegion[], ISpellChecker, ISpellingProblemCollector, IProgressMonitor)`
vs 
https://github.com/grosenberg/Fluentmark/blob/10e7e6cb7b0e653fd100f9beb3bc002877445df2/net.certiv.fluent.dt.ui/src/main/java/net/certiv/fluent/dt/ui/editor/spell/SpellingEngine.java#L42

**Comment by iloveeclipse** [comment]
And *why* is fluentmark editor is used for the spelling engine at all? According to the reporter, that seem to happened without explicit user action?

**Comment by cdietrich** [comment]
the spelling engine shows up in the spelling preference dialog. the question is: why is it selected or picked although its off by default https://github.com/grosenberg/Fluentmark/blob/f0d3412da74f19a58818985de59f7ca19bc0c665/net.certiv.fluent.dt.ui/plugin.xml#L302

maybe the user forgot that they selected it or there is another mechanism that leads to it be picked

**Comment by iloveeclipse** [comment]
I see on fresh install that it "defaults" to the fluentmark spelling engine, without any user interaction. That must be fixed.
