### ISSUE TITLE
Some characters not correctly rendered with Pandoc

### ISSUE THREAD

**Issue by mrgou** [grosenberg/Fluentmark#59]
If I select `pandoc` (2.11) as a converter, some characters are not correctly rendered in the viewer:

- Apostrophes
- Quotation marks enclosing text

![Screenshot 2021-01-11 152029](https://user-images.githubusercontent.com/5311753/104194010-0cc7b280-5421-11eb-8836-eaeb7c611410.png)

- Latin extended characters

...even though the file is UTF-8 (conversion error when accented characters are inserted)!
![Screenshot 2021-01-11 152102](https://user-images.githubusercontent.com/5311753/104194026-118c6680-5421-11eb-8d2a-3975db36d76b.png)

This even affects the HTML output:

```html
<body>
<p>Punctuation: . , ; ? !</p>
<p>An apostrophe: Ã¢â‚¬â„¢</p>
<p>A quotation mark: "</p>
<p>Two quotation marks around text: Ã¢â‚¬Å“aÃ¢â‚¬ï¿½</p>
<p>Digits: 1234567890</p>

</body>
```

On the other hand, running the conversion from `pandoc` directly (`pandoc -t html -o test.html test.md`):

```html
<p>Punctuation: . , ; ? !</p>
<p>An apostrophe: ’</p>
<p>A quotation mark: "</p>
<p>Two quotation marks around text: “a”</p>
<p>Digits: 1234567890</p>
<p>Extended latin characters: é</p>
```

This does not happen with other converters (which, on the other hand, don't handle tables correctly...)

**Comment by grosenberg** [comment]
Finally tracked this down to a UTF-8 issue. Fixed in the next release.
