### ISSUE TITLE
Unable to install from Eclipse Marketplace

### ISSUE THREAD

**Issue by wlfbck** [grosenberg/Fluentmark#62]
Title basically. In Eclipse 2021-03 the installation fails with the following error:
The following solutions are not available: FluentMark 1.6.0 (id=net.certiv.fluentmark.feature.feature.group, site=http://www.certiv.net/updates)

**Comment by grosenberg** [comment]
The install works if done directly from  the update site (https://www.certiv.net/updates)

The marketplace metadata seems not to have updated properly,
