### ISSUE TITLE
FluentMark Viewer: "The BROWSE action is not supported on the current platform!"

### ISSUE THREAD

**Issue by Equiphract** [grosenberg/Fluentmark#64]
When having opened a Markdown file in Eclipse and then clicking the "Open FluentMark Viewer" in the toolbar I get the following error dialog:

![Error Dialog](https://user-images.githubusercontent.com/31915427/114853590-3c050b80-9de4-11eb-9fad-dc01392d3070.png)

This is the Eclipse error log output:
```
!ENTRY org.eclipse.core.jobs 4 2 2021-04-15 11:44:19.837
!MESSAGE An internal error occurred during: "Open Liveview".
!STACK 0
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
	at net.certiv.fluent.dt.vis.util.LiveUtil.openBrowser(LiveUtil.java:232)
	at net.certiv.fluent.dt.vis.util.LiveUtil.openBrowser(LiveUtil.java:221)
	at net.certiv.fluent.dt.vis.handlers.OpenLiveHandler$1.run(OpenLiveHandler.java:66)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
The button "Export as HTML" does work after installing and linking pandoc to the plugin. The button "Export as PDF" however does not seem to work. I don't get an error message and there is no entry in the Eclipse error log, however the PDF file is not generated.

I skimmed over your code and saw, that you run `xdg-open` on Linux platforms for the Viewer functionality. I tried opening an HTML file using `xdg-open file.html` and it opened it in my default browser, so that seems to work.

I am running ArchLinux with [DWM](https://dwm.suckless.org/) as a window manager. The installed default browser is Firefox 87.0 (64-bit).

**Comment by grosenberg** [comment]
What java distribution and version is being used.

Your java is returning `true` from `Desktop.isDesktopSupported()` -- that should only occur for MS Windows. That is why Fluentmark is failing to open the live view using a Windows only call `Desktop.getDesktop().browse(url.toURI());`

**Comment by Equiphract** [comment]
```shell
[me@mars ~]$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
```

**Comment by grosenberg** [comment]
Requires testing.

https://www.dropbox.com/s/mds8dgelaxfwjcq/net.certiv.fluent.dt.site-1.6.3-SNAPSHOT.zip?dl=0

**Comment by Equiphract** [comment]
Installed it.

New error dialog:
![image](https://user-images.githubusercontent.com/31915427/114927361-a8f2c280-9e31-11eb-8946-28e3a1bf7456.png)

Eclipse error log output has changed as well:
```
!ENTRY org.eclipse.core.jobs 4 2 2021-04-15 21:28:16.211
!MESSAGE An internal error occurred during: "Open Liveview".
!STACK 0
java.lang.NullPointerException: Job of type net.certiv.fluent.dt.vis.handlers.OpenLiveHandler$1 returned no status.
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:81)
```

**Comment by grosenberg** [comment]
Try again.

https://www.dropbox.com/s/elpv04px8suf22z/net.certiv.fluent.dt.site-1.6.3-SNAPSHOT.zip?dl=0

Also, be sure that only one instance of the workbench is running.  The error message suggests that the address/port for the websocket server was already in use.

**Comment by Equiphract** [comment]
Ok, I tested this version and the live view worked, no error dialog, no Eclipse error log entry:

> https://www.dropbox.com/s/elpv04px8suf22z/net.certiv.fluent.dt.site-1.6.3-SNAPSHOT.zip?dl=0

I went back and tested this version again and it worked as well, no idea what I did wrong while testing this version yesterday:
> https://www.dropbox.com/s/mds8dgelaxfwjcq/net.certiv.fluent.dt.site-1.6.3-SNAPSHOT.zip?dl=0

Then I went back to the marketplace version and tried it, but the same error persists:

```
!ENTRY org.eclipse.core.jobs 4 2 2021-04-16 08:28:03.544
!MESSAGE An internal error occurred during: "Open Liveview".
!STACK 0
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
	at net.certiv.fluent.dt.vis.util.LiveUtil.openBrowser(LiveUtil.java:232)
	at net.certiv.fluent.dt.vis.util.LiveUtil.openBrowser(LiveUtil.java:221)
	at net.certiv.fluent.dt.vis.handlers.OpenLiveHandler$1.run(OpenLiveHandler.java:66)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by grosenberg** [comment]
Continue to use the 1.6.3 version for now.  The public update site will be updated soon.
