### ISSUE TITLE
Eclipse problem reporting has weird behaviour when encountering a colon (":")

### ISSUE THREAD

**Issue by Equiphract** [grosenberg/Fluentmark#65]
When a colon character is written on the first line of a file it behaves as expected:
![image](https://user-images.githubusercontent.com/31915427/115861266-e5767d80-a432-11eb-8206-0ea4ebe9fb9b.png)

When written on the second line eclipse (or the plugin rather) displays the error `Md: No viable alternative for input 'test:' at 2:5 ':' <COLON>` in the "Problems" view and the line does not show up in the file outline anymore:
![image](https://user-images.githubusercontent.com/31915427/115861486-2078b100-a433-11eb-98a6-1adf92bcbae1.png)
This also happens, when something else is written on the line above.

When written on any line after that it behaves normally again.

---

This behaviour also occurs when there are 3 consecutive lines and the third one has a colon character in it. The 3 lines can be written anywhere in the file, the behaviour stays the same:
![image](https://user-images.githubusercontent.com/31915427/115862137-07bccb00-a434-11eb-813c-418424c2dacd.png)
With this variant however I get the following error message for location 7:6:
```
Md: Extraneous input ':' expecting {<eof>, word, comment, code_beg,
html_block_beg, yaml_block, dot_block, math_block, tex_block,
uml_block, maths, span, url, urltag, html, tex, unicode, entity,
image, fnote, link, table, pipe, hashes, hrule, bullet_mark,
numb…
```

Operating System: Arch Linux
Converter: Flexmark

**Comment by grosenberg** [comment]
Fixed.
