### ISSUE TITLE
"[]" in a table caused Fluentmark to drop remainder of table

### ISSUE THREAD

**Issue by mmoser18** [grosenberg/Fluentmark#72]
When describing APIs we often use "[]" after an entry to signal that the parameter is an array, e.g. here the `Name` argument (2nd line):

```
|destinationAccess             |Enum     |Either `Dciq`, `Deot`, or None.        |
|replyToQueue                  |Name[]   |List of `replyToQueue` (=`dcrq`)       |
|validFrom                     |Timestamp|Date and time from which this is valid.|
|expiresAt                     |Timestamp|Date and time at which this expires.   |
```

If we define such a line in the markdown file and reformat that table using the Fluentmark editor it will drop that line and all subsequent ones of the table. :-(  It also "wiggles" such brackets as faulty (not clear what it expects here...)

Expected behviour: the presence of "[]" should not bother the reformatting but rather be included "as-is". It also should not highlight these lines as faulty. 

If the "[]" is meant for other purposes then that should be configurable...

**Comment by mmoser18** [comment]
As I just discovered, a ':' (colon) in the text causes the same issue. It is shown with wiggles and that line plus all subsequent ones get dropped.
Example:
```
| Event        | Description                                    |
|--------------|------------------------------------------------|
| msgReceived  | A msg. was received. Payload: messages content |
| msgProcessed | A msg. was processed. Payload: result code     |
```

**Comment by grosenberg** [comment]
Major change in the parser necessary to implement the fix.

**Comment by mmoser18** [comment]
Thanks for fixing this! As I just noticed, however, it also has issues with text in quotes (' or ") while backticks ` work. 
I had opened another issue describing that but for some reason I can't locate it right now (already closed?). Please make sure, it also accepts word that are quoted. We often use that in SW documentation to denote "literals" like Constants to be used like in `legal values are 'active', 'completed', 'deleted'`
