### ISSUE TITLE
Live View Flexmark converter html comment not closed properly

### ISSUE THREAD

**Issue by geodab** [grosenberg/Fluentmark#74]
When using the Flexmark converter the rendering in the Live View sometimes drops content.  This seems to happen only for some types of diagrams, for example when using `@startyaml . . . @endyaml` or  `@startwbs . . . @endwbs` or when only including `version` or `note` inside of `@startuml . . . @enduml`.  When this happens, switching to view the code shows that the HTML comment that wraps the MD5 tagged plantuml code block inside the svg is not closed properly because the trailing `-->` is replaced with `--&gt;`.  If the comment is subsequently closed, for example by a properly rendered block, then that block is also hidden but the following content then becomes visible again.

As a workaround, it seems that this snippet can be used to force the comment closure to occur with limited impact to rendering outside of the Live View:

    ```plantuml
    @startuml
    class ClassA
    hide ClassA
    class ClassB
    hide ClassB
    @enduml
    ```

Attached are example files for some markdown and the corresponding code view that exhibits the problem and above workaround.

Eclipse: 2023-03 (4.27.0)
Plugin: FluentMark Editor 1.8.0.20230519-1831
[Fluentmark-test-notes.md](https://github.com/grosenberg/Fluentmark/files/11629842/Fluentmark-test-notes.md)
[Fuentmark-test-notes.md.code.txt](https://github.com/grosenberg/Fluentmark/files/11629844/Fuentmark-test-notes.md.code.txt)

**Comment by grosenberg** [comment]
The `--&gt;` shows in the generated source for all four diagrams, not just the one that does not display correctly.  That indicates that this is a PlantUML, not Fluentmark, issue.

**Comment by geodab** [comment]
Sorry if the example was not clear.

Yes, the code for each of the 4 note diagrams is incorrect, but the example was intended to illustrate that the class diagram inserted after the 2nd note allows the 3rd note to be displayed normally because the class diagram properly closes the html comment.

With the Flexmark converter only notes 1 and 3 are shown in the Live View for the example, but with the Pandoc converter selected all 4 are shown along with the paragraph text referring to the hidden class diagram.

Both converters seem to be using the same PlantUML version 1.2022.4, as indicated inside the html comments. That's not to say that PlantUML isn't still also involved somehow, but it only seems to be triggered by the Flexmark converter pathway, and only for some diagrams.

For reference, I've also attached here the code generated for the example markdown when the Pandoc converter is selected, which does not exhibit the problem.

[Fluentmark-test-notes.md.code-pandoc.txt](https://github.com/grosenberg/Fluentmark/files/11637380/Fluentmark-test-notes.md.code-pandoc.txt)

**Comment by grosenberg** [comment]
Ok, so a Flexmark issue.  Internally, Fluentmark makes essentially no distinction between the different converters.

Is there a particular reason you are using Flexmark over Pandoc?  No hard numbers, but I believe most users use Pandoc now that it has full Commonmark compatibility. 

Likely that Flexmark and the other converters will be removed in a future version of Fluentmark.

**Comment by geodab** [comment]
Ok, thanks, good to know that the Pandoc converter is the preferred option, so I'll try sticking to that.  I had been switching between the two while trying to isolate some other rendering issues and simply isolated this one first.

I think the other issue I'm seeing is related to using '$' in quoted names which sometimes inadvertently gets interpreted as inline math and I'm not sure how to escape it, but that happens for both converters and whether or not 'Mathjax rendering' is enabled.  One curious difference however (aside from the html comment issue), is that the rendering problem goes away with the Flexmark converter after I toggle to the 'code' view and then back to the 'live' view, at which point everything with an embedded '$' appears correct.  Unfortunately this navigational workaround fails when the Pandoc converter is enabled, which is why I've been switching between them.  If I can demonstrate this other problem in a simple example I'll try to open a separate ticket for it.

**Comment by grosenberg** [comment]
Thanks.
