### ISSUE TITLE
Table editor not working ?

### ISSUE THREAD

**Issue by olberger** [grosenberg/Fluentmark#77]
I'm using Eclipse 2023-12.

I've tried adding the following markdown table (copied from the docs):
```
|Key             |Function                                         |
|:---------------|:------------------------------------------------|
|Ctrl-Space      |Open quick assist popup                          |
|Ctrl-1          |Spellcheck quick correct                         |
|Ctrl-b          |Toggle **bold** of selected text                 |
|Ctrl-i          |Toggle _italics_ of selected text                |
|Ctrl-/          |Toggle Markdown-style commenting of selected text|
|Ctrl-Shift-/    |Toggle HTML-style commenting of selected text    |
|Ctrl-Shift-F    |Format - full page or selected text              |
|Alt-Shift-Y     |Toggle soft line wrap                            |
```

The docs mention "To open the table editor pop-up, `double-click` an existing markdown table.", but ... where should one double-click ?

I see nothing double-clickable. Just the source code in the regular font...

The "Table" button in the editor toolbar seems inactive.

However the markdown preview in the live view works for this syntax.

Or is another alternative markdown table syntax needed for the table editor to operate ?

I don't think so as the Ctrl-space helper generates a table with such a syntax.

Thanks in advance.

**Comment by grosenberg** [comment]
To open the table editor, `double-click` *anywhere within* an existing table *in the editor window*.
