### ISSUE TITLE
Wrap pasted text

### ISSUE THREAD

**Issue by jouvin** [grosenberg/fluentmark#8]
It'd be nice if FluentMark editor would wrap a text pasted in a MD document. Currently, only the text directly entered (from the keyboard) is wrapped.

**Comment by grosenberg** [comment]
Use Ctrl-Shift-F to format selected text or the entire page. See "Use" at the bottom of the README.

**Comment by jouvin** [comment]
My point is that I found painful to do such a thing at each paste operation. It'd be nice to have it done automatically, at least if a preference says to tell it.

BTW, I trided CTRL-Shift-F on a whole page but it messed up all the item list level (nested item lists).
