### ISSUE TITLE
compile from source missing DSL editor

### ISSUE THREAD

**Issue by defect-track** [grosenberg/Fluentmark#81]
Installing latest version throws a "java.lang.NoSuchMethodError" properly because I'm not on the latest and greatest Eclipse. 

To debug it further I downloaded the sources and tried to compile via Maven. Unfortunately there is one reference to "net.certiv.dsl" where I can't find the sources or GitHub project.

Would it be possible to point me into the right direction where I can find them?

Thanks in advance

**Comment by grosenberg** [comment]
The current Fluentmark release is compatible with at least the last four Eclipse releases. What version are you targeting?

**Comment by defect-track** [comment]
Done some more digging and the issue is Eclipse dropped support for macOS Catalina in latest 2024-03 release. Looking at the Fluentmark code it is builds against Eclipse latest. As such it pulls in 2024-03 binaries which breaks Eclipse due to the drop of Catalina support.
Unfortunately I can't go higher than Catalina with my Mac until I get a better one. If you can provide a version that binds against 2023-12 or earlier it would solve my problem. Alternative I can build it on my own if you can point me to the dsl sources.

**Comment by grosenberg** [comment]
Fluentmark currently requires Java 17 and, even though the build is against 'latest', the generated plugin code is specified as compatible with at least Eclipse 2023-04 and higher.  Fluentmark should install just fine on Eclipse 2023-12 as it does not rely on anything that is Catalina specific.  If not, please provide the log files showing the install/execution issue.

**Comment by defect-track** [comment]
I understand your explanation how it should work but sometimes the devil is in the detail ;-)

Eclipse can sometimes a beast when it comes to resolving and installing dependencies. In this case or my case it clearly doesn't do a great job on installing software as explained above and you end up with a broken installation. (tested it multiple times). However, was able to find a workaround which required to edit all Eclipse update urls. You just need to replace all "eclipse.org/..../latest" to "eclipse.org/..../2023-12". Depending on your configuration there are 3 or more of them. 
Steps required are:

- go to "Install New Software"
- click on the manage button
- edit each "Eclipse..." entry
- finally "Apply and Close"
- quit Eclipse
- start Eclipse
- go to "Install New Software"
- click on the dropdown and verify if all URL's are pointing to 2023-12
- add the Fluentmark repository
- install and enjoy

This worked perfect for me with a brand new 2023-12 Eclipse download and my production version.

Hope this helps others stuck on an older MacOS release.

Thanks for a great MarkDown editor.
