### ISSUE TITLE
Ctrl-Shift-F does not work

### ISSUE THREAD

**Issue by jouvin** [grosenberg/fluentmark#9]
In fact this is a follow-up for #8 that I cannot reopen... I cannot manage to get Ctrl-Shift-F to work, not sure why... I'd the feeling it worked once on the whole text (with the result of messing it up). My last comment in #8 (https://github.com/grosenberg/fluentmark/issues/8#issuecomment-288958342) still applies...

**Comment by grosenberg** [comment]
Works for me. You will have to provide more detail to get help.

**Comment by grosenberg** [comment]
For code blocks, both the opening and closing ``` mark must be on its own line. If not, it is a markdown syntax error and the formatter will not process past that point.

**Comment by jouvin** [comment]
I'd have hapilly provided more details but if you close the issue immediatly, I cannot...
